#### GET ALL
GET http://localhost:3001/api/blogs

#### INSERTAR
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title": "Prueba de POST",
    "author": "Juancito",
    "url": "www.prueba.net",
    "likes": "10"
}

#### Most Blogs
GET http://localhost:3001/api/blogs/mostBlogs

#### Most Likes
GET http://localhost:3001/api/blogs/mostLikes
