#### GET ALL
GET http://localhost:3001/api/blogs

#### INSERTAR
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
    "title": "Prueba de POST",
    "author": "Mario",
    "url": "www.prueba.net",
    "likes": "2"
}

#### Most Blogs
GET http://localhost:3001/api/blogs/mostBlogs
